export const recipes = [
  {
    _id: "1",
    name: "Pizza recipe",
    image: "/images/pizza.jpg",
    ingredients: ["pepperonies", "cheese", "flour", "onions", "chicken"],
    instructions: ["Boil water", "Pour pepperonies"],
    rating: 4,
    numReviews: 19,
    description:
      "Very cool recipe. Makes your next delicacy delicious jhefd gyuvdfv cuyvub eruygvygy n 9v ggrhf hicn94hf nuh h h98f 89h8 8 8hf8 h 8h huher houer hheh9 huhdin oiv uns iunco ininio sniucn",
  },
  {
    _id: "2",
    name: "Burger recipe",
    image: "/images/burger.jpg",
    ingredients: ["pepperonies", "cheese", "flour", "onions", "chicken"],
    instructions: ["Boil water", "Pour pepperonies"],
    rating: 2,
    numReviews: 44,
    description: "Very cool recipe. Makes your next delicacy delicious",
  },
  {
    _id: "3",
    name: "Fries recipe",
    image: "/images/fries.jpg",
    ingredients: ["pepperonies", "cheese", "flour", "onions", "chicken"],
    instructions: ["Boil water", "Pour pepperonies"],
    rating: 3.5,
    numReviews: 12,
    description: "Very cool recipe. Makes your next delicacy delicious",
  },
  {
    _id: "4",
    name: "cake recipe",
    image: "/images/cake.jpg",
    ingredients: ["flour", "sugar", "color"],
    instructions: ["Mix in water", "add sugar"],
    rating: 4.5,
    numReviews: 25,
    description: "Very cool recipe. Makes your next delicacy delicious",
  },
];
