export const LIST_RECIPES_REQUEST = "LIST_RECIPES_REQUEST";
export const LIST_RECIPES_SUCCESS = "LIST_RECIPES_SUCCESS";
export const LIST_RECIPES_FAIL = "LIST_RECIPES_FAIL";

export const GET_RECIPE_BY_ID_REQUEST = "GET_RECIPE_BY_ID_REQUEST";
export const GET_RECIPE_BY_ID_SUCCESS = "GET_RECIPE_BY_ID_SUCCESS";
export const GET_RECIPE_BY_ID_FAIL = "GET_RECIPE_BY_ID_FAIL";
export const GET_RECIPE_BY_ID_RESET = "GET_RECIPE_BY_ID_RESET";
